language: node_js
node_js:
  - 9.9.0

cache:
  directories:
  - node_modules

branches:
  only:
  - master

install:
  yarn install

script:
  - yarn run build


deploy:
  provider: heroku
  api_key:
    secure: c2c25c30-9f99-4200-a9c8-855943be71b8
  app: react-issues-view
  local_dir: build
  on:
    repo: egorAva/react-issues-view