language: node_js
node_js:
  - 9.9.0

cache:
  directories:
  - node_modules

branches:
  only:
  - master

install:
  yarn install

script:
  - yarn build


deploy:
  provider: heroku
  api_key:
    secure: $API_KEY
  app: react-issues-view
  skip_cleanup: true
  local_dir: build
  on:
    repo: egorAva/react-issues-view